name: Build iOS App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Xcode Project
        run: |
          xcodebuild build -project "Go Guide.xcodeproj" -scheme "Go Guide" -sdk iphoneos CODE_SIGNING_ALLOWED=NO

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-file
          path: build/**/*.app
